# Generated by Django 3.2 on 2021-08-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.CharField(max_length=15)),
                ('goods', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('type', models.CharField(max_length=10)),
                ('page', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeMultidata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_multidata', models.JSONField()),
            ],
        ),
    ]
