# Generated by Django 3.2 on 2021-08-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_prepare', '0004_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miniWallkey', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=15)),
                ('details', models.JSONField()),
            ],
        ),
    ]
