# Generated by Django 3.2 on 2021-08-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('phoneNumber', models.IntegerField()),
                ('countBalance', models.IntegerField(null=True)),
                ('coupon', models.IntegerField(null=True)),
                ('coinPoint', models.IntegerField(null=True)),
                ('message', models.CharField(max_length=100, null=True)),
                ('cart', models.JSONField()),
            ],
        ),
    ]
