# Generated by Django 3.2 on 2021-09-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_alter_userinfo_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='sessionId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
